=== NCIP/caimage/src/gov/nih/nci/caIMAGE/util/calcrgn.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<!ELEMENT Catalog (Image)>
<!ATTLIST Catalog
	name CDATA #REQUIRED
>
<!ELEMENT Image EMPTY>
<!ATTLIST Image
	rgn CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	parent CDATA #REQUIRED
	numlevels CDATA #REQUIRED
	colorspace CDATA #REQUIRED
>
<!ELEMENT ImageServer (Request, Response)>
<!ATTLIST ImageServer
	host CDATA #REQUIRED
	path CDATA #REQUIRED
	xmlns:LizardTech CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA)>
<!ATTLIST Parameter
	name (cat | hei | img | style | wid) #REQUIRED
>
<!ELEMENT Request (Parameter+)>
<!ATTLIST Request
	command CDATA #REQUIRED
>
<!ELEMENT Response (Catalog)>

=== NCIP/caimage/src/gov/nih/nci/caIMAGE/util/calcrgn.xml
<?xml version="1.0" encoding="utf-8"?>

<!--L
  Copyright SAIC (Corporate).

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/caimage/LICENSE.txt for details.
L-->

<!DOCTYPE ImageServer SYSTEM "calcrgn.dtd">
<ImageServer host="165.112.113.105:80" path="lizardtech/iserv" xmlns:LizardTech="http://www.lizardtech.com">
	<Request command="calcrgn">
		<Parameter name="cat">MouseProstateNormal</Parameter>
		<Parameter name="img">MP19.sid</Parameter>
		<Parameter name="wid">400</Parameter>
		<Parameter name="hei">400</Parameter>
		<Parameter name="style">none</Parameter>
	</Request>
	<Response>
		<Catalog name="MouseProstateNormal">
			<Image rgn="0.2545315488,0.2708764912,0.7440152964,0.7280520037" name="MP19.sid" type="sid" width="26150" height="27998" parent="/" numlevels="6" colorspace="RGB"/>
		</Catalog>
	</Response>
</ImageServer>
